# Generated by Django 4.2.6 on 2025-05-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_code',
            field=models.CharField(choices=[('I', '출근'), ('O', '퇴근')], max_length=1, verbose_name='근무코드'),
        ),
    ]
