# Generated by Django 4.2.6 on 2024-01-04 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wtm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_date', models.DateField()),
                ('type', models.CharField(max_length=20)),
                ('check_yn', models.CharField(max_length=1)),
                ('reg_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('fri', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fri', to='wtm.module')),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='con_mod_id', to=settings.AUTH_USER_MODEL)),
                ('mon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mon', to='wtm.module')),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='con_reg_id', to=settings.AUTH_USER_MODEL)),
                ('sat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sat', to='wtm.module')),
                ('sun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sun', to='wtm.module')),
                ('thu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='thu', to='wtm.module')),
                ('tue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tue', to='wtm.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_id', to=settings.AUTH_USER_MODEL)),
                ('wed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wed', to='wtm.module')),
            ],
        ),
    ]
