# Generated by Django 4.2.6 on 2025-11-26 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wtm', '0002_alter_work_work_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='비콘명')),
                ('uuid', models.CharField(max_length=64)),
                ('major', models.IntegerField()),
                ('minor', models.IntegerField()),
                ('max_distance_meters', models.FloatField(default=3.0, verbose_name='최대 인식 거리(m)')),
                ('rssi_threshold', models.IntegerField(default=-65, verbose_name='RSSI 임계값(dBm)')),
                ('tx_power', models.IntegerField(default=-59, verbose_name='Tx Power')),
                ('stabilize_count', models.IntegerField(default=3, verbose_name='연속 인식 횟수')),
                ('timeout_seconds', models.IntegerField(default=10, verbose_name='시간초과(초)')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('memo', models.TextField(blank=True, verbose_name='비고')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('mod_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='beacon',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beacons', to='common.branch', verbose_name='지점'),
        ),
        migrations.AddField(
            model_name='beacon',
            name='mod_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beacon_mod_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='beacon',
            name='reg_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beacon_reg_id', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='beacon',
            unique_together={('branch', 'uuid', 'major', 'minor')},
        ),
    ]
