# Generated by Django 5.1.4 on 2025-12-08 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtm', '0003_beacon_remove_work_unique_workcode_per_day_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'permissions': [('bypass_beacon', 'Can bypass beacon requirement for attendance')]},
        ),
    ]
