# Generated by Django 5.1.4 on 2025-12-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wtm', '0004_alter_work_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'permissions': [('bypass_beacon', '비콘 바이패스 권한')]},
        ),
    ]
