# Generated by Django 5.1.4 on 2025-12-12 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtm', '0005_alter_work_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_code',
            field=models.CharField(choices=[('I', '출근'), ('O', '퇴근')], max_length=1, verbose_name='근로코드'),
        ),
    ]
