# Generated by Django 5.1.4 on 2025-12-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtm', '0006_alter_work_work_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='meal_amount',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='식대(원)'),
        ),
        migrations.AlterField(
            model_name='module',
            name='cat',
            field=models.CharField(max_length=20, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='module',
            name='end_time',
            field=models.CharField(max_length=5, verbose_name='종업시각'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=50, verbose_name='근로명'),
        ),
        migrations.AlterField(
            model_name='module',
            name='rest1_end_time',
            field=models.CharField(max_length=5, verbose_name='휴게1종료시각'),
        ),
        migrations.AlterField(
            model_name='module',
            name='rest1_start_time',
            field=models.CharField(max_length=5, verbose_name='휴게1시작시각'),
        ),
        migrations.AlterField(
            model_name='module',
            name='rest2_end_time',
            field=models.CharField(max_length=5, verbose_name='휴게2종료시각'),
        ),
        migrations.AlterField(
            model_name='module',
            name='rest2_start_time',
            field=models.CharField(max_length=5, verbose_name='휴게2시작시각'),
        ),
        migrations.AlterField(
            model_name='module',
            name='start_time',
            field=models.CharField(max_length=5, verbose_name='시업시각'),
        ),
    ]
