# Generated by Django 4.2.6 on 2025-12-20 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wtm', '0007_module_meal_amount_alter_module_cat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
