# Generated by Django 4.2.6 on 2024-02-15 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=20)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_mod_id', to=settings.AUTH_USER_MODEL)),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='position_reg_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_name', models.CharField(max_length=20)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('reg_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dept_mod_id', to=settings.AUTH_USER_MODEL)),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dept_reg_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
