# Generated by Django 4.2.6 on 2024-03-10 00:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='mod_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stand_date', models.DateField()),
                ('mon', models.CharField(max_length=1)),
                ('tue', models.CharField(max_length=1)),
                ('wed', models.CharField(max_length=1)),
                ('thu', models.CharField(max_length=1)),
                ('fri', models.CharField(max_length=1)),
                ('sat', models.CharField(max_length=1)),
                ('sun', models.CharField(max_length=1)),
                ('reg_date', models.DateTimeField()),
                ('mod_date', models.DateTimeField()),
                ('mod_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_mod_id', to=settings.AUTH_USER_MODEL)),
                ('reg_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='business_reg_id', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
