# Generated by Django 4.2.6 on 2025-11-27 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='common.branch', verbose_name='지점'),
        ),
        migrations.AlterField(
            model_name='user',
            name='dept',
            field=models.CharField(max_length=50, verbose_name='부서명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='기기정보'),
        ),
        migrations.AlterField(
            model_name='user',
            name='emp_name',
            field=models.CharField(max_length=20, verbose_name='직원명'),
        ),
        migrations.AlterField(
            model_name='user',
            name='join_date',
            field=models.DateField(null=True, verbose_name='입사일자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='out_date',
            field=models.DateField(blank=True, null=True, verbose_name='퇴사일자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=50, verbose_name='직위명'),
        ),
    ]
