# Generated by Django 4.2.6 on 2025-12-08 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_user_branch_alter_user_dept_alter_user_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_employee',
            field=models.BooleanField(default=True, help_text='직원목록 및 근태 관리 대상인 사용자인지 여부입니다.', verbose_name='근태/직원목록 대상 여부'),
        ),
    ]
