# Generated by Django 5.1.4 on 2025-12-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_user_is_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('web_access', '웹 페이지 접속 권한')], 'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
